#
# Pebble build rules for From Here. FH_TEST_MINUTE pins the clock for emulator screenshots
# and is never set for a distributable build.
#
import os

top = '.'
out = 'build'


def options(ctx):
    ctx.load('pebble_sdk')


def configure(ctx):
    ctx.load('pebble_sdk')


def build(ctx):
    ctx.load('pebble_sdk')
    binaries = []
    cached_env = ctx.env
    for platform in ctx.env.TARGET_PLATFORMS:
        ctx.env = ctx.all_envs[platform]
        test_minute = os.environ.get('FH_TEST_MINUTE')
        if test_minute is not None:
            test_minute = int(test_minute)
            if not 0 <= test_minute < 1440:
                ctx.fatal('FH_TEST_MINUTE must be 0..1439')
            ctx.env.append_value('DEFINES', 'FH_TEST_MINUTE=%d' % test_minute)
        ctx.set_group(ctx.env.PLATFORM_NAME)
        app_elf = '{}/pebble-app.elf'.format(ctx.env.BUILD_DIR)
        ctx.pbl_build(source=ctx.path.ant_glob('src/c/**/*.c'), target=app_elf, bin_type='app')
        binaries.append({'platform': platform, 'app_elf': app_elf})
    ctx.env = cached_env
    ctx.set_group('bundle')
    ctx.pbl_bundle(binaries=binaries,
                   js=ctx.path.ant_glob(['src/pkjs/**/*.js', 'src/pkjs/**/*.json']),
                   js_entry_file='src/pkjs/index.js')
